create table if not exists public.recipes (
  id bigint primary key generated by default as identity,
  name text not null,
  source text not null default 'Our kitchen',
  page integer,
  time integer not null default 30,
  servings integer not null default 4,
  emoji text not null default '🍽️',
  photo text not null default 'photo-3',
  tag text not null default 'New',
  ingredients jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.recipes add column if not exists tags jsonb not null default '[]'::jsonb;
alter table public.recipes add column if not exists page integer;

alter table public.recipes enable row level security;

drop policy if exists "Authenticated users can view recipes" on public.recipes;
drop policy if exists "Anyone can view recipes" on public.recipes;
create policy "Anyone can view recipes" on public.recipes for select to anon, authenticated using (true);

drop policy if exists "Authenticated users can add recipes" on public.recipes;
drop policy if exists "Anyone can add recipes" on public.recipes;
create policy "Anyone can add recipes" on public.recipes for insert to anon, authenticated with check (true);

drop policy if exists "Authenticated users can edit recipes" on public.recipes;
drop policy if exists "Anyone can edit recipes" on public.recipes;
create policy "Anyone can edit recipes" on public.recipes for update to anon, authenticated using (true) with check (true);

alter table public.recipes replica identity full;
alter publication supabase_realtime add table public.recipes;
